version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASS}"
      MYSQL_DATABASE: "${MYSQL_SCHEMA}"
    ports:
      - "3306:3306"
    volumes:
      - "/Users/rafaeldurelli/Documents/development/golang/parserLogTest/volume"
